### ISSUE TITLE
Can't access kirby objects in {pattern}.config.php

### ISSUE THREAD

**Issue by jakobploens** [getkirby/patterns#1]
There's no return when using one of the kirby variables ($page/$pages/$site) in a config file, only works when using it directly in the html file. Using `site()`, `pages()` or `page()` returns the correct class, but without any data.

**Comment by bastianallgeier** [comment]
The variables are not injected into the config, but using site() and page() should work. At least it works here. pages() is not available.

**Comment by jakobploens** [comment]
Okay, that was my mistake – the other ones are working, just pages() is missing, yes. Is there a particular reason for it? Nevertheless, issue can be closed.

**Comment by bastianallgeier** [comment]
To be honest, pages shouldn't be there in the first place. It's a relict from the very first version. The name implies too much that the variable contains ALL THE PAGES. That's why I prefer to use $site->children() now, but I can't remove this relict unfortunately.
