### ISSUE TITLE
Give patterns a title [feature request]

### ISSUE THREAD

**Issue by jakobploens** [getkirby/patterns#2]
Would be great to have the ability to give patterns a title that will show up in the sidebar. Especially for clients it would be much easier (with clients who don't speak english) to give certain patterns a valid name which is easy recognizable. Could be the same syntax as with Kirby; if the title field is missing, just use the folder name as it is right now.

**Comment by bastianallgeier** [comment]
Good idea! Would be a good additional option for the config file.

**Comment by bastianallgeier** [comment]
https://github.com/getkirby/patterns/blob/master/readme.md#title
