### ISSUE TITLE
Set certain view as default [feature request]

### ISSUE THREAD

**Issue by jakobploens** [getkirby/patterns#3]
Would be great if one would be able to set a certain view as default, e.g. the preview one. If clients are using the pattern lab (as a styleguide), it would be much more comfortable if they have directly the preview instead of some weird code they can't understand (well, otherwise they wouldn't have hired us…)

**Comment by bastianallgeier** [comment]
Another good point!! I think it could be handled via the global config.

**Comment by bastianallgeier** [comment]
https://github.com/getkirby/patterns/blob/master/readme.md#patternspreviewmode
