### ISSUE TITLE
Import css without preprocessor

### ISSUE THREAD

**Issue by molocLab** [getkirby/patterns#6]
Is it possible to import css into page (ex. header.php) directly from the pattern?

Something like:

`<?php echo css('site/patterns/pattern/pattern.css') ?>`

doesn't seem to work.

**Comment by bastianallgeier** [comment]
If you've checked out the latest version you can do: 

```php
<?php echo css('patterns/pattern/pattern.css?raw=true') ?>
```
But be aware that this should only be used for testing. This will be routed through the pattern app and add an overhead of PHP fetching and displaying the CSS.
